# Generated by Django 2.1.7 on 2019-03-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'data_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=3000, null=True, unique=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'page_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=500, null=True)),
                ('robots_content', models.TextField(blank=True, null=True)),
                ('sitemap_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('from_page', models.ForeignKey(db_column='from_page', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='from_page', serialize=False, to='sites.Page')),
            ],
            options={
                'db_table': 'link',
                'managed': False,
            },
        ),
    ]
