# Generated by Django 2.1.7 on 2019-03-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'data_type',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=3000, null=True, unique=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('accessed_time', models.DateTimeField(blank=True, null=True)),
                ('crawl_delay', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(blank=True, null=True)),
                ('data_type_code', models.ForeignKey(blank=True, db_column='data_type_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.DataType')),
            ],
            options={
                'db_table': 'page_data',
            },
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'page_type',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=500, null=True)),
                ('robots_content', models.TextField(blank=True, null=True)),
                ('sitemap_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('from_page', models.ForeignKey(db_column='from_page', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='from_page', serialize=False, to='sites.Page')),
            ],
            options={
                'db_table': 'link',
            },
        ),
        migrations.AddField(
            model_name='pagedata',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type_code',
            field=models.ForeignKey(blank=True, db_column='page_type_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.PageType'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sites.Page'),
        ),
        migrations.AddField(
            model_name='link',
            name='to_page',
            field=models.ForeignKey(db_column='to_page', on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_page', to='sites.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('from_page', 'to_page')},
        ),
    ]
