# Generated by Django 2.1.7 on 2019-03-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
    ]
