# Generated by Django 2.1.7 on 2019-03-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_auto_20190320_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='crawl_delay',
            field=models.IntegerField(default=4),
        ), ]
